"""
validate_graph.py — comprehensive structural + protocol validator for
graph_runner-schema graph.yaml files.

WHY THIS EXISTS: graph_runner.py's Graph.load() does NOT validate
structure at all -- confirmed directly against its source: it just
reads whatever fields exist in the YAML, filling defaults for missing
optional ones. There's no check that the backbone exists, that
`parent` references resolve, that `dependencies` reference real
nodes, that a parent's dependencies actually include its children (the
schema rule violated by the real expense_split_calculator bug found
earlier), or that a node's children match what its declared
`interface.protocol` is allowed to contain. Those checks previously
existed only scattered across incidental crashes in graph_runner.py's
OTHER methods, JS-only code in the browser viewer/editor
(graph-model.js), and one-off inspection scripts written ad hoc during
this project. This consolidates all of it into one reusable,
CLI-runnable checker any graph.yaml can be run through -- hand-authored,
generated by the repo importer, or edited via graph_editor.html --
before it's trusted.

The protocol registry here is a deliberate Python port of the same one
in graph-model.js (the browser editor) -- kept in sync by hand for
now. If the two drift, the editor's `+ Custom protocol type`
registrations won't be visible here; see the note in main() output
when an unknown protocol is encountered.

REVISION 3: `rest`/`python-module`/`python-function` renamed to
`entrypoint`/`module`/`function` (language-agnostic protocol names --
no protocol string implies Python anymore except `browser-js`, which
is deliberately untouched, frontend being a separate future design
effort). `language` moved from a fixed per-protocol registry constant
to per-node data, resolved by walking up to the nearest `module`
ancestor that declares one (see resolve_language). `model_fields`
changed from a flat {name: type} map to a list of {name, type, ...}
objects, matching enum_values/constants/methods' existing shape.
Function `signature` (a free-text string) is retired in favor of
structured `params`/`returns`, reusing `contract.methods`' own shape.
Every type reference (model_fields, params, returns, methods,
class.fields) is now a structured TYPE_DESCRIPTOR -- a real node id or
a canonical primitive keyword, or a fully-nested list/map/optional
wrapper -- never a string requiring a parser. See the accepted
Revision 3 proposal doc for the full design rationale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from graph_runner import Graph, Node, Status


PROTOCOL_REGISTRY = {
    "entrypoint": {"allowed_children": {"module", "function", "data-model"}, "required_fields": []},
    "module": {"allowed_children": {"function", "module", "data-model", "contract", "class"}, "required_fields": []},
    "function": {"allowed_children": set(), "required_fields": ["params", "returns"]},
    # Deliberately UNCHANGED by Revision 3 -- frontend is a separate,
    # future design effort. Still carries a fixed `language` constant
    # (the OLD per-protocol mechanism); resolve_language() below checks
    # for this before falling back to the new ancestor-walk.
    "browser-js": {"allowed_children": set(), "required_fields": ["exports"], "language": "javascript"},
    # required_fields is only the baseline ("model_kind" -- every
    # data-model node needs to declare which kind it is); the
    # kind-specific fields (model_fields vs enum_type/enum_values vs
    # constants) are checked separately in check 5, since a flat
    # required_fields list can't express "model_fields is required
    # UNLESS model_kind is enum/constant" -- see MODEL_KIND_REQUIRED_FIELDS.
    "data-model": {"allowed_children": set(), "required_fields": ["model_kind"]},
    # contract: a fixed set of method signatures, not executable code
    # -- see graph_runner.py's NON_EXECUTABLE_PROTOCOLS for the runtime
    # side of this.
    "contract": {"allowed_children": set(), "required_fields": ["methods"]},
    # class: a concrete implementation of a contract. `implements` is
    # validated separately (not via required_fields, same reasoning as
    # maps_to/implements not being registry `fields`: it's a top-level
    # relationship, not an interface field). `fields` (Revision 3, new)
    # IS a real interface field -- a class's own instance state --
    # required so every class explicitly declares it (even as `[]`)
    # rather than leaving it ambiguous whether it was just forgotten.
    "class": {"allowed_children": {"function"}, "required_fields": ["fields"]},
}

MODEL_KIND_ENUM = {"dto", "db_schema", "enum", "constant"}  # mirrors graph-model.js's MODEL_KIND_VALUES

# Which interface sub-field(s) each model_kind actually requires --
# replaces a single flat "model_fields is always required" assumption,
# which would have produced a false warning on every enum/constant
# node (neither has model_fields; they have enum_values/constants
# instead). Checked directly against model_kind in check 5, not via
# PROTOCOL_REGISTRY's required_fields (which has no way to express a
# condition on another field's value).
MODEL_KIND_REQUIRED_FIELDS = {
    "dto": ["model_fields"],
    "db_schema": ["model_fields"],
    "enum": ["enum_type", "enum_values"],
    "constant": ["constants"],
}

# Revision 3's canonical, language-neutral scalar vocabulary -- NOT
# Python's own type names (no "str"/"int", no PEP 604 "X | None" union
# syntax). Mirrors graph-model.js's CANONICAL_PRIMITIVE_TYPES exactly.
# "none" is valid only as a function's `returns` type (no value).
CANONICAL_PRIMITIVE_TYPES = {
    "string", "integer", "float", "boolean", "decimal", "datetime", "uuid", "none",
}
TYPE_WRAPPER_KINDS = {"list", "map", "optional"}


def resolve_type_descriptor(desc, graph: Graph) -> str | None:
    """Mirrors graph-model.js's checkTypeDescriptorShape, PLUS the
    existence check that function can't do live against nodes that
    might not be loaded yet in the editor -- this is the authoritative
    check. Returns None if `desc` is a legal type descriptor (a
    canonical primitive, a real node id, or a wrapper whose nested
    descriptor(s) are themselves legal), or an error string otherwise.
    Recurses for list/map/optional -- no depth limit, since a type
    descriptor is a finite YAML structure, not a string to parse."""
    if not isinstance(desc, dict) or "type" not in desc:
        return "a type descriptor needs a 'type' key"
    t = desc["type"]
    if t in CANONICAL_PRIMITIVE_TYPES:
        return None
    if t == "list":
        if "items" not in desc:
            return "type: list needs an 'items' descriptor"
        return resolve_type_descriptor(desc["items"], graph)
    if t == "map":
        if "key" not in desc or "value" not in desc:
            return "type: map needs 'key' and 'value' descriptors"
        err = resolve_type_descriptor(desc["key"], graph)
        return err if err else resolve_type_descriptor(desc["value"], graph)
    if t == "optional":
        if "of" not in desc:
            return "type: optional needs an 'of' descriptor"
        return resolve_type_descriptor(desc["of"], graph)
    # Anything else must be a real node id -- this is the check that
    # replaces Revision 2's raw-snake-case-id-vs-derived-PascalCase-name
    # mistake entirely: under Revision 3 the node id IS the type name,
    # so there's no wrong form left to type, only "does this id exist."
    if t not in graph.nodes:
        return f"'{t}' is neither a canonical primitive ({sorted(CANONICAL_PRIMITIVE_TYPES)}) nor an existing node id"
    return None


def resolve_language(node: Node, graph: Graph, registry: dict) -> str | None:
    """Revision 3: a node's effective language is resolved by walking
    up from itself through `parent`, looking for the nearest ancestor
    `module` that declares `interface.language`, falling back to
    `graph.default_language`, then None if nothing anywhere declares
    one at all. Exception: a protocol whose OWN registry entry still
    carries a fixed `language` constant (today, only browser-js --
    deliberately untouched by Revision 3) uses that directly, before
    the walk -- mirrors graph-model.js's resolveLanguage exactly."""
    proto = node.interface.get("protocol")
    rule = registry.get(proto)
    if rule and rule.get("language"):
        return rule["language"]

    cur: Node | None = node
    while cur is not None:
        if cur.interface.get("protocol") == "module" and cur.interface.get("language"):
            return cur.interface["language"]
        cur = graph.nodes.get(cur.parent) if cur.parent else None
    return graph.default_language


def load_full_registry(graph_path: Path) -> tuple[dict, list[str]]:
    """Starts from the 7 built-in protocols and merges in any custom
    ones found in the YAML's top-level `protocol_registry` block (the
    same block graph_editor.html now writes on export -- see its
    graphToYamlObject()). This is what makes the validator generic
    instead of hardcoded to whatever protocols ship by default.

    Returns (registry, warnings) -- a custom entry that collides with
    a built-in id is skipped with a warning, never silently overwritten.

    Field-name note: the JS export uses `allowedChildren` (camelCase)
    and has no `required_fields` concept at all (it has `fields`,
    a broader "what does this protocol's form show" list, which is
    NOT the same thing as "what MUST be present once this node is
    past unsplit"). Rather than guess which of a custom protocol's
    `fields` should be required, restored custom protocols get
    required_fields=[] -- no invented requirement, an honest gap
    stated here rather than a guessed one. Custom protocols still
    declare a fixed `language` the OLD way (this function's job is
    restoring what the editor's "+ Custom protocol type" modal wrote,
    which hasn't itself been migrated to Revision 3's per-node
    mechanism) -- not touched by this revision.
    """
    registry = {k: dict(v) for k, v in PROTOCOL_REGISTRY.items()}
    warnings = []

    raw = yaml.safe_load(graph_path.read_text())
    custom_block = (raw or {}).get("protocol_registry")
    if not custom_block:
        return registry, warnings

    for proto_id, js_def in custom_block.items():
        if proto_id in registry:
            warnings.append(
                f"protocol_registry entry '{proto_id}' in the graph file collides with "
                f"a built-in protocol id -- keeping the built-in definition, ignoring this one"
            )
            continue
        if "language" not in js_def:
            warnings.append(
                f"protocol_registry entry '{proto_id}' has no 'language' -- skipping it, "
                f"cross-language boundary checks won't apply to nodes using this protocol"
            )
            continue
        registry[proto_id] = {
            "allowed_children": set(js_def.get("allowedChildren", [])),
            "required_fields": [],  # see docstring -- not invented from `fields`
            "language": js_def["language"],
        }

    return registry, warnings


def validate(graph: Graph, registry: dict = PROTOCOL_REGISTRY) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []

    # 1. Backbone must exist.
    if graph.backbone not in graph.nodes:
        errors.append(f"backbone '{graph.backbone}' does not exist among nodes")
        return errors, warnings  # nothing else can be meaningfully checked

    # 2. No dangling parent references.
    for n in graph.nodes.values():
        if n.parent and n.parent not in graph.nodes:
            errors.append(f"node '{n.id}' has parent '{n.parent}' which does not exist")

    # 3. No dangling dependency references.
    for n in graph.nodes.values():
        for dep_id in n.dep_ids:
            if dep_id not in graph.nodes:
                errors.append(f"node '{n.id}' depends on '{dep_id}' which does not exist")

    # 3b. No dangling maps_to references -- same category of check as
    #     #3 above, just for the `maps_to` relationship (a type mapping,
    #     e.g. a DB schema node -> the DTO it's realized as) rather than
    #     `dependencies` (a call). Mirrors graph-model.js's
    #     computeMapsToEdges dangling flag, which is what surfaces this
    #     same problem visually (a red dotted line) in graph_editor.html.
    for n in graph.nodes.values():
        for target_id in n.maps_to_ids:
            if target_id not in graph.nodes:
                errors.append(f"node '{n.id}' maps_to '{target_id}' which does not exist")

    # 3c. implements target(s) must actually be `contract` nodes -- a
    #     dangling check (mirrors #3b for maps_to) plus a type check
    #     (mirrors graph-model.js's addImplements, which enforces this
    #     at authoring time; this catches a hand-edited graph that
    #     bypassed the editor). Kept as its own pass, not nested inside
    #     check 5, so it still runs even for a node whose OWN protocol
    #     isn't recognized (check 5 skips those nodes entirely).
    for n in graph.nodes.values():
        for target_id in n.implements_ids:
            target = graph.nodes.get(target_id)
            if target is None:
                errors.append(f"node '{n.id}' implements '{target_id}' which does not exist")
            elif target.interface.get("protocol") != "contract":
                errors.append(
                    f"node '{n.id}' implements '{target_id}', but that node has protocol "
                    f"'{target.interface.get('protocol')}', not 'contract'"
                )

    # 3j. No dangling calls references -- a call-graph edge sharpening
    #     a `dependencies` entry down to a named operation. Mirrors 3b/
    #     3c's dangling-reference pattern for this new relationship
    #     (see graph-model.js's addCall doc comment for why it's a
    #     separate top-level field rather than folded into dependencies).
    for n in graph.nodes.values():
        for c in n.calls:
            target_id = c if isinstance(c, str) else c.get("node")
            if target_id not in graph.nodes:
                errors.append(f"node '{n.id}' calls '{target_id}' which does not exist")

    # 3k. No dangling data_flows references -- same category of check,
    #     for the data_flows relationship (see graph-model.js's
    #     addDataFlow doc comment).
    for n in graph.nodes.values():
        for d in n.data_flows:
            target_id = d if isinstance(d, str) else d.get("node")
            if target_id not in graph.nodes:
                errors.append(f"node '{n.id}' has a data_flow to '{target_id}' which does not exist")
            data_model = None if isinstance(d, str) else d.get("data_model")
            if data_model and data_model not in graph.nodes:
                warnings.append(
                    f"node '{n.id}' has a data_flow referencing data_model "
                    f"'{data_model}' which does not exist as a node"
                )

    # 3d. contract method param/return types must resolve as real
    #     TYPE_DESCRIPTORs (Revision 3) -- a canonical primitive, a
    #     real node id, or a fully-nested list/map/optional wrapper.
    #     Error-level now (not warning): under Revision 3 there's no
    #     ambiguity left to be lenient about -- a type descriptor
    #     either resolves or it's simply wrong, unlike Revision 2's
    #     bare-string heuristic unwrapping.
    for n in graph.nodes.values():
        if n.interface.get("protocol") != "contract":
            continue
        for m in n.interface.get("methods", []):
            for p in m.get("params", []):
                err = resolve_type_descriptor(p.get("type"), graph)
                if err:
                    errors.append(f"node '{n.id}' method '{m.get('name')}' param '{p.get('name')}': {err}")
            err = resolve_type_descriptor(m.get("returns"), graph)
            if err:
                errors.append(f"node '{n.id}' method '{m.get('name')}' returns: {err}")

    # 3e. function params/returns must resolve the same way.
    for n in graph.nodes.values():
        if n.interface.get("protocol") != "function":
            continue
        for p in n.interface.get("params", []):
            err = resolve_type_descriptor(p.get("type"), graph)
            if err:
                errors.append(f"node '{n.id}' param '{p.get('name')}': {err}")
        if "returns" in n.interface:
            err = resolve_type_descriptor(n.interface["returns"], graph)
            if err:
                errors.append(f"node '{n.id}' returns: {err}")

    # 3f'. class.fields must resolve the same way too.
    for n in graph.nodes.values():
        if n.interface.get("protocol") != "class":
            continue
        for f in n.interface.get("fields", []):
            err = resolve_type_descriptor(f.get("type"), graph)
            if err:
                errors.append(f"node '{n.id}' field '{f.get('name')}': {err}")

    # 3g. layout, when set, must be a recognized value and only ever
    #     appear on `module` (class was deliberately excluded -- a
    #     class's methods belong together in one file). An EXPLICIT
    #     layout: file is now also checked for real: it's only valid
    #     if every direct child is protocol "function" -- Revision 3
    #     makes this an enforced rule, not just documented convention
    #     (see the accepted proposal §7). Leaving `layout` unset is
    #     always fine; the correct value is inferred at generation time.
    LAYOUT_ENUM = {"file", "folder"}
    for n in graph.nodes.values():
        layout = n.interface.get("layout")
        if layout is None:
            continue
        if n.interface.get("protocol") != "module":
            errors.append(f"node '{n.id}' sets layout='{layout}' but is protocol="
                           f"'{n.interface.get('protocol')}' -- layout only applies to module")
            continue
        if layout not in LAYOUT_ENUM:
            errors.append(f"node '{n.id}' has layout='{layout}', not one of {sorted(LAYOUT_ENUM)}")
            continue
        if layout == "file":
            children = graph.children_of(n.id)
            non_function = [c.id for c in children if c.interface.get("protocol") != "function"]
            if non_function:
                errors.append(
                    f"node '{n.id}' has layout='file' but has non-function child(ren) "
                    f"{sorted(non_function)} -- a module can only be layout: file if "
                    f"EVERY direct child is a function; set layout: folder instead "
                    f"(or remove layout to let it be inferred automatically)"
                )

    # 3h. http_method/route must be set TOGETHER on a `function` node,
    #     or not at all -- generate_main_file() (scaffold.py) only
    #     wires an endpoint when BOTH are present, so one without the
    #     other silently produces no route with no warning from that
    #     generator itself. Catching it here instead.
    for n in graph.nodes.values():
        if n.interface.get("protocol") != "function":
            continue
        has_method = bool(n.interface.get("http_method"))
        has_route = bool(n.interface.get("route"))
        if has_method != has_route:
            missing = "route" if has_method else "http_method"
            warnings.append(
                f"node '{n.id}' has {'http_method' if has_method else 'route'} set but "
                f"not '{missing}' -- generate_main_file() requires both to wire an "
                f"endpoint for this function; as-is it silently gets no route."
            )

    # 3i. model_fields (Revision 3: a LIST of {name, type, ...}
    #     objects, not a flat {name: type} map) -- each entry needs a
    #     `name` and a resolvable `type` descriptor. This is also
    #     where Revision 2's raw-snake-case-id mistake check used to
    #     live; it's gone because that mistake is no longer expressible
    #     -- see resolve_type_descriptor's docstring.
    for n in graph.nodes.values():
        if n.interface.get("protocol") != "data-model":
            continue
        mf = n.interface.get("model_fields")
        if not isinstance(mf, list):
            continue  # not a dto/db_schema node, or genuinely absent -- checked separately below
        names = [f.get("name") for f in mf]
        dupes = {x for x in names if names.count(x) > 1}
        if dupes:
            errors.append(f"node '{n.id}' has duplicate model_fields name(s): {sorted(dupes)}")
        for f in mf:
            if "name" not in f:
                errors.append(f"node '{n.id}': a model_fields entry is missing 'name'")
                continue
            err = resolve_type_descriptor(f.get("type"), graph)
            if err:
                errors.append(f"node '{n.id}' field '{f['name']}': {err}")

    # 4. A parent's dependencies must include ALL its children -- the
    #    established schema rule (violated once already by the real
    #    expense_service/expense_split_calculator bug this project hit).
    for n in graph.nodes.values():
        children_ids = {c.id for c in graph.children_of(n.id)}
        if children_ids:
            missing = children_ids - set(n.dep_ids)
            if missing:
                errors.append(
                    f"node '{n.id}' has children {sorted(missing)} missing from "
                    f"its own dependencies list (a split node must list every "
                    f"child it created, since it literally calls them)"
                )

    # 5. Protocol-based structural rules (child-type compatibility, per
    #    the same registry graph_editor.html enforces at creation time
    #    -- this is what catches a bad graph that was hand-edited
    #    outside the editor, bypassing that enforcement).
    for n in graph.nodes.values():
        proto = n.interface.get("protocol")
        if proto not in registry:
            warnings.append(
                f"node '{n.id}' has protocol '{proto}', not in the built-in registry "
                f"and not found in this file's own protocol_registry block either -- "
                f"skipping protocol-specific checks for it. If this was registered as "
                f"a custom protocol in graph_editor.html, make sure the file was "
                f"exported (not just edited in-session) so its protocol_registry "
                f"block was actually written."
            )
            continue
        rule = registry[proto]
        children = graph.children_of(n.id)
        if children and not rule["allowed_children"]:
            errors.append(
                f"node '{n.id}' (protocol={proto}) has children "
                f"{sorted(c.id for c in children)} but this protocol allows none"
            )
        else:
            for c in children:
                c_proto = c.interface.get("protocol")
                if c_proto not in rule["allowed_children"]:
                    errors.append(
                        f"node '{n.id}' (protocol={proto}) has child '{c.id}' "
                        f"with protocol '{c_proto}', not an allowed child type "
                        f"(allowed: {sorted(rule['allowed_children']) or '(none)'})"
                    )
        for field in rule["required_fields"]:
            if n.status != Status.UNSPLIT.value and field not in n.interface:
                warnings.append(
                    f"node '{n.id}' (protocol={proto}, status={n.status}) is "
                    f"missing expected interface field '{field}'"
                )
        if proto == "data-model" and "model_kind" in n.interface:
            model_kind = n.interface["model_kind"]
            if model_kind not in MODEL_KIND_ENUM:
                errors.append(
                    f"node '{n.id}' has model_kind='{model_kind}', not one of "
                    f"{sorted(MODEL_KIND_ENUM)} (mirrors graph-model.js's MODEL_KIND_VALUES)"
                )
            else:
                # Kind-specific required fields -- see
                # MODEL_KIND_REQUIRED_FIELDS's comment for why this
                # can't live in PROTOCOL_REGISTRY's flat required_fields.
                for kind_field in MODEL_KIND_REQUIRED_FIELDS[model_kind]:
                    if n.status != Status.UNSPLIT.value and kind_field not in n.interface:
                        warnings.append(
                            f"node '{n.id}' (model_kind={model_kind}, status={n.status}) is "
                            f"missing expected interface field '{kind_field}'"
                        )
                if model_kind == "enum":
                    names = [v.get("name") for v in n.interface.get("enum_values", [])]
                    dupes = {x for x in names if names.count(x) > 1}
                    if dupes:
                        errors.append(f"node '{n.id}' has duplicate enum_values name(s): {sorted(dupes)}")
                if model_kind == "constant":
                    names = [c.get("name") for c in n.interface.get("constants", [])]
                    dupes = {x for x in names if names.count(x) > 1}
                    if dupes:
                        errors.append(f"node '{n.id}' has duplicate constants name(s): {sorted(dupes)}")

    # 6. Status/test consistency -- a node can't honestly claim tested/
    #    integrated with zero tests (mirrors graph_runner.py's OWN
    #    resync rule, but checked here without needing to run any tests).
    for n in graph.nodes.values():
        if n.status in (Status.TESTED.value, Status.INTEGRATED.value) and not n.tests:
            errors.append(
                f"node '{n.id}' claims status='{n.status}' but has no tests -- "
                f"per the schema this should be impossible via normal resync; "
                f"check for a stale or hand-edited status field"
            )

    # 7. Node-id / generated-path collision risk -- mirrors the real
    #    a2d bug (a node named 'models' colliding with 'models.action_item'
    #    at the filesystem level once scaffolded). Flagged as a warning,
    #    not an error, since module_scaffold.py now handles this
    #    correctly -- but worth knowing about before scaffolding.
    ids = set(graph.nodes.keys())
    for id_ in ids:
        if any(other != id_ and other.startswith(id_ + ".") for other in ids):
            warnings.append(
                f"node '{id_}' is a dotted-prefix of other node id(s) (e.g. "
                f"'{id_}.x') -- module_scaffold.py handles this correctly "
                f"(routes '{id_}' into a package __init__.py), but scaffold.py's "
                f"leaf-granularity mode was never tested against this pattern; "
                f"double-check its output if you use --granularity leaf here"
            )

    # 8. Cross-language dependency edges must declare boundary=service.
    #    'parent' means "this code literally lives inside that module's
    #    file" -- impossible across languages, so this rule only applies
    #    to `dependencies`. boundary=module across a language boundary
    #    would claim a same-process direct call that's physically
    #    impossible; only boundary=service (a real network/IPC call) can
    #    legitimately cross a language line. Revision 3: language is
    #    resolved per-node (resolve_language), not looked up as a fixed
    #    registry constant -- see that function's docstring.
    for n in graph.nodes.values():
        n_proto = n.interface.get("protocol")
        if n_proto not in registry:
            continue  # already warned about in check 5
        n_lang = resolve_language(n, graph, registry)
        for dep_id in n.dep_ids:
            dep = graph.nodes.get(dep_id)
            if dep is None:
                continue  # already an error from check 3
            if dep.interface.get("protocol") not in registry:
                continue
            dep_lang = resolve_language(dep, graph, registry)
            if n_lang is None or dep_lang is None:
                continue  # neither side makes a language claim -- can't compare against unknown
            if n_lang != dep_lang:
                effective_boundary = n.boundary or graph.default_boundary
                if effective_boundary != "service":
                    errors.append(
                        f"node '{n.id}' ({n_lang}) depends on '{dep_id}' "
                        f"({dep_lang}) -- a cross-language edge but "
                        f"boundary='{effective_boundary}', not 'service'. A same-process "
                        f"direct call ('module') is physically impossible across "
                        f"languages; set boundary: service on '{n.id}' (a real network/IPC call)."
                    )

    return errors, warnings


def main():
    ap = argparse.ArgumentParser(description="Validate a graph_runner-schema graph.yaml")
    ap.add_argument("graph_file", type=Path)
    ap.add_argument("--quiet", action="store_true", help="Only print errors, suppress warnings")
    args = ap.parse_args()

    graph = Graph.load(args.graph_file)
    registry, registry_warnings = load_full_registry(args.graph_file)
    errors, warnings = validate(graph, registry)
    warnings = registry_warnings + warnings

    if not args.quiet:
        for w in warnings:
            print(f"WARNING: {w}")
    for e in errors:
        print(f"ERROR: {e}")

    if errors:
        print(f"\n{len(errors)} error(s), {len(warnings)} warning(s) -- INVALID")
        sys.exit(1)
    else:
        print(f"\n0 errors, {len(warnings)} warning(s) -- VALID")
        sys.exit(0)


if __name__ == "__main__":
    main()
